package com.acrutchfield.natashashairstudio.viewmodel;

import android.app.Application;

import com.acrutchfield.natashashairstudio.Utils;
import com.acrutchfield.natashashairstudio.data.FirestoreQueryLivedata;
import com.acrutchfield.natashashairstudio.model.Review;
import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QuerySnapshot;

import java.util.List;

import androidx.annotation.NonNull;
import androidx.arch.core.util.Function;
import androidx.lifecycle.AndroidViewModel;
import androidx.lifecycle.LiveData;
import androidx.lifecycle.Transformations;

public class ReviewViewModel extends AndroidViewModel {


    private static final String ORDER_BY_DATE = "date";
    private static final String ID = "id";
    private FirebaseFirestore db = FirebaseFirestore.getInstance();
    private CollectionReference reviewsRef = db.collection("/REVIEWS");

    private final FirestoreQueryLivedata liveData = new FirestoreQueryLivedata(reviewsRef, ORDER_BY_DATE);
    private final LiveData<List<Review>> liveDataReviews = Transformations.map(liveData, new Deserializer());

    public ReviewViewModel(@NonNull Application application) {
        super(application);
    }

    public LiveData<List<Review>> getLiveDataReviews() {
        return liveDataReviews;
    }

    public void addReview(Review review) {
        reviewsRef.add(review)
                .addOnSuccessListener(
                        documentReference -> {
                            // Get the autogenerated ID
                            documentReference.update(ID, documentReference.getId());
                            Utils.notifyUser("We appreciate your feedback!",
                                    getApplication().getBaseContext());
                        }
                )
                .addOnFailureListener(
                        e -> Utils.notifyUser("Failure. Check your network connection.",
                                getApplication().getBaseContext()));
    }

    private class Deserializer implements Function<QuerySnapshot, List<Review>> {

        @Override
        public List<Review> apply(QuerySnapshot input) {
            return input.toObjects(Review.class);
        }
    }

    // TODO: Implement the ViewModel
}
